# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fridayUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Friday(object):
    def setupUi(self, Friday):
        Friday.setObjectName("Friday")
        Friday.resize(1394, 852)
        self.centralwidget = QtWidgets.QWidget(Friday)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1401, 851))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:/Downloads/5136471.webp"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(650, 400, 91, 31))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:0.52 rgba(0, 0, 0, 0), stop:0.565 rgba(82, 121, 76, 33), stop:0.65 rgba(159, 235, 148, 64), stop:0.721925 rgba(255, 238, 150, 129), stop:0.77 rgba(255, 128, 128, 204), stop:0.89 rgba(191, 128, 255, 64), stop:1 rgba(0, 0, 0, 0));\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(65, 246, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1290, 10, 93, 28))
        self.pushButton_2.setStyleSheet("background-color: rgb(24, 24, 24);\n"
"background-color: rgb(6, 231, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 120, 151, 151))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:/Users/Lenovo/Downloads/05bd96100762b05b616fb2a6e5c223b4.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 750, 1391, 81))
        self.label_3.setStyleSheet("gridline-color: rgb(28, 225, 255);\n"
"border-color: rgb(35, 244, 255);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("C:/Users/Lenovo/Downloads/jjxe0tre9jftihzqp4aw.gif" ))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(880, 10, 161, 51))
        self.textBrowser.setStyleSheet("background-color: rgb(0, 115, 125);\n"
"font: 75 italic 16pt \"Rockwell\";")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(1060, 10, 161, 51))
        self.textBrowser_2.setStyleSheet("background-color: rgb(0, 115, 125);\n"
"font: 75 italic 16pt \"Rockwell\";")
        self.textBrowser_2.setObjectName("textBrowser_2")
        Friday.setCentralWidget(self.centralwidget)

        self.retranslateUi(Friday)
        QtCore.QMetaObject.connectSlotsByName(Friday)

    def retranslateUi(self, Friday):
        _translate = QtCore.QCoreApplication.translate
        Friday.setWindowTitle(_translate("Friday", "MainWindow"))
        self.pushButton.setText(_translate("Friday", "Start"))
        self.pushButton_2.setText(_translate("Friday", "Exit"))
        self.textBrowser.setHtml(_translate("Friday", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Rockwell\'; font-size:18pt; font-weight:72; font-style:italic;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\"><br /></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("Friday", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Rockwell\'; font-size:18pt; font-weight:72; font-style:italic;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Friday = QtWidgets.QMainWindow()
    ui = Ui_Friday()
    ui.setupUi(Friday)
    Friday.show()
    sys.exit(app.exec_())
